theme = "lynx"
title = "Portfolio Templates"
baseURL= "https://jalcocert.github.io/templates/"


enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "IoTechCrafts Web Portfolio"
  headline = """
  Having a modern website doesn't have to be hard (neither 💰)
  """
  
  image = "fossengineer.png" 
  links = [
    { linkedin = "https://www.linkedin.com/" },
    { fossengineer = { href = "https://cyclingthere.com/", text = "Cycling Blog" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true