theme = "lynx"
title = "Portfolio Templates"
baseURL= "https://jalcocert.github.io/templates/"


enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "IoTechCrafts Web Portfolio"
  headline = """
  Having a modern website doesn't have to be hard (neither 💰)
  """
  bottomline = """
  Others will tell you that it is hard to even try to have a Web.

  We make it **easy for you**.
  """
  
  image = "fossengineer.png" 
  links = [
    { font-awesome = { href = "https://cyclingthere.com/", text = "Sample Web 1" } },
    { font-awesome = { href = "https://ioracing.iotechcrafts.com//", text = "Sample Web 2" } },
    { font-awesome = { href = "https://iodoctor.iotechcrafts.com//", text = "Sample Web 3" } },

    { linkedin = "https://www.linkedin.com/" },
    { twitter = "https://x.com" },
  ]

  links_firm = [

    { iotech = { href = "https://iotechcrafts.com/", text = "Check Out IoTechCrafts" } },       

  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true