theme = "lynx"
title = "Portfolio Templates"
baseURL= "https://jalcocert.github.io/templates/"


enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "IoTechCrafts Web Portfolio"
  headline = """
  Having a modern website doesn't have to be hard (neither 💰)
  """
  bottomline = """
  Others will tell you that it is hard to even try to have a Web.

  We make it **easy for you**.
  """
  
  image = "IoTech.png" 
  links = [
    { font-awesome = { href = "https://cyclingthere.com/", text = "Sample Web 1 - Story Blog" } },
    { font-awesome = { href = "https://ioracing.iotechcrafts.com/", text = "Sample Web 2" } },
    { font-awesome = { href = "https://iodoctor.iotechcrafts.com/", text = "Sample Web 3" } },
    { font-awesome = { href = "https://iot.iotechcrafts.com/", text = "Sample Web 4" } },
    { font-awesome = { href = "https://iotechcrafts.github.io/astroverse/", text = "Sample 5 - Image Centered Blog" } },
    { font-awesome = { href = "https://github.com/IoTechCrafts/astro-bento-portfolio-ssg", text = "Sample 6 - Bento Portfolio" } },
    { font-awesome = { href = "https://github.com/IoTechCrafts/canvas-SSG", text = "Sample 7 - Portfolio Canvas" } },
    { font-awesome = { href = "https://github.com/IoTechCrafts/stablo-astro-SSG", text = "Sample 8 - Stablo Template" } },
    { font-awesome = { href = "https://github.com/IoTechCrafts/hugo-theme-gallery-ssg", text = "Sample 9 - Gallery Theme" } },
    { font-awesome = { href = "https://github.com/IoTechCrafts/hugo-theme-stack", text = "Sample 10 - Card Style Theme" } },

    { linkedin = "https://www.linkedin.com/" },
    { twitter = "https://x.com" },
  ]

  links_firm = [

    { iotech = { href = "https://iotechcrafts.com/", text = "Check Out IoTechCrafts" } },       

  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true